import type { AgentSpec } from "../shared/schema.ts";

/** The provider-scoped launch settings shared by agents, profiles, and policy overrides. */
export interface LaunchConfig {
  provider: string;
  model?: string;
  modeId?: string;
  thinkingOptionId?: string;
  featureValues?: Record<string, unknown>;
}

export interface AgentProfileLike {
  id: string;
  name: string;
  provider: string;
  model?: string;
  modeId?: string;
  thinkingOptionId?: string;
  featureValues?: Record<string, unknown>;
}

export type ResolvedReviewer =
  | { ok: true; config: LaunchConfig & { model: string }; source: string; note?: string }
  | { ok: false; error: string };

/**
 * Provider features normally inherit from the source agent. Plan mode is the exception: a turn in that mode ends
 * with a plan-approval request instead of the structured reply that a gate-managed role must return. It is keyed by
 * the feature, not the provider name: the same Codex adapter also runs as "codex-proxy" or under other ids.
 */
export function prepareManagedLaunch(config: LaunchConfig & { model: string }): LaunchConfig & { model: string } {
  if (!Object.hasOwn(config.featureValues ?? {}, "plan_mode")) return config;
  return {
    ...config,
    featureValues: { ...config.featureValues, plan_mode: false },
  };
}

function findProfile(profiles: readonly AgentProfileLike[], ref: string): AgentProfileLike | string {
  const byId = profiles.find((profile) => profile.id === ref);
  if (byId) return byId;
  const byName = profiles.filter((profile) => profile.name === ref);
  if (byName.length === 1) return byName[0];
  const names = profiles.map((profile) => `"${profile.name}" (${profile.id})`).join(", ") || "none";
  return byName.length > 1
    ? `agent profile name "${ref}" is ambiguous; use its id. Profiles: ${names}`
    : `agent profile "${ref}" not found. Profiles: ${names}`;
}

/**
 * Layers the reviewer config: source agent → agent profile → explicit policy fields.
 * Model, mode, thinking and features are provider-specific, so a layer that switches
 * provider drops everything inherited from lower layers instead of mixing them.
 */
export function resolveReviewer(
  source: LaunchConfig,
  spec: Partial<Omit<AgentSpec, "profile">> & { profile?: string | null },
  profiles: readonly AgentProfileLike[],
): ResolvedReviewer {
  const layers: Array<{ label: string; config: Partial<LaunchConfig> }> = [];
  if (spec.profile) {
    const profile = findProfile(profiles, spec.profile);
    if (typeof profile === "string") return { ok: false, error: profile };
    layers.push({ label: `profile "${profile.name}"`, config: profile });
  }
  const explicit: Partial<LaunchConfig> = {
    ...(spec.provider ? { provider: spec.provider } : {}),
    ...(spec.model ? { model: spec.model } : {}),
    ...(spec.mode ? { modeId: spec.mode } : {}),
    ...(spec.thinking ? { thinkingOptionId: spec.thinking } : {}),
    ...(spec.features ? { featureValues: spec.features } : {}),
  };
  if (Object.keys(explicit).length > 0) layers.push({ label: "policy fields", config: explicit });

  let config: LaunchConfig = { ...source };
  let label = "source agent";
  for (const layer of layers) {
    if (layer.config.provider && layer.config.provider !== config.provider) {
      config = { provider: layer.config.provider };
    }
    config = {
      ...config,
      ...(layer.config.model ? { model: layer.config.model } : {}),
      ...(layer.config.modeId ? { modeId: layer.config.modeId } : {}),
      ...(layer.config.thinkingOptionId ? { thinkingOptionId: layer.config.thinkingOptionId } : {}),
      ...(layer.config.featureValues
        ? { featureValues: { ...config.featureValues, ...layer.config.featureValues } }
        : {}),
    };
    label = layer.label;
  }
  if (!config.model) {
    return { ok: false, error: `no model resolved for provider "${config.provider}" (from ${label}); set model` };
  }
  return { ok: true, config: { ...config, model: config.model }, source: label };
}

/**
 * Resolves a role's launch config. New policies default to no profile. The historical role profile ids remain
 * optional so policies generated by older releases keep inheriting the source agent when those profiles are absent.
 */
export function resolveRole(
  source: LaunchConfig,
  spec: Partial<Omit<AgentSpec, "profile">> & { profile?: string | null },
  defaultProfile: string,
  profiles: readonly AgentProfileLike[],
): ResolvedReviewer {
  const missingDefault = spec.profile === defaultProfile && !profiles.some((profile) => profile.id === defaultProfile);
  const resolved = resolveReviewer(source, { ...spec, profile: missingDefault ? null : spec.profile }, profiles);
  if (!resolved.ok) return resolved;
  const managed = { ...resolved, config: prepareManagedLaunch(resolved.config) };
  if (!missingDefault) return managed;
  return {
    ...managed,
    note: `legacy profile "${defaultProfile}" does not exist, so the source agent's settings were used; set profile to null to remove this legacy reference`,
  };
}
